### ISSUE TITLE
What causes elm.js elm-stuff to be produced? Can it be configured to live outside of the source directory?

### ISSUE THREAD

**Issue by dnk8n** [alexkorban/elmstatic#12]
In experimenting with some dockerized services, and `elmstatic watch`, when I make a change to how things are configured I very often get the following

```
-- CORRUPT BINARY ----- /root/.elm/0.19.0/package/Skinney/murmur3/2.0.8/objs.dat

The binary data at /root/.elm/0.19.0/package/Skinney/murmur3/2.0.8/objs.dat is
corrupt.

Elm caches build artifacts in the following directories:

    /root/.elm
    elm-stuff/

Maybe you recently installed a command line tool or editor plugin that messes
with them? They definitely should not be doing that, but you never know! So
maybe try deleting them? Everything will be rebuilt from scratch. This may help
reveal the corrupting influence.

```

Trashing the container does not help, so the problem is actually to do in elm-stuff directory. I can remove these contents and start a new container and everything works as expected.

I can't seem to find much information about this elm-stuff directory (and similarly elm.js) that are found in the source directory by default. It is fine that they remain there by default, but is there a way to configure their locations? Because then a `named docker volume` can be configured to hold this data while the source is `bind mounted`.

**Comment by alexkorban** [comment]
`elm-stuff/` is a cache for build artifacts produced by the Elm compiler. As far as I know, its location cannot be changed. 

`elm.js` is the result of compiling the Elm source. Its location could be configured, but I have no plans to make it configurable at present. 

I noticed, however, that the error message points to `/root/.elm` rather than `elm.js` or `elm-stuff/`.
