### ISSUE TITLE
Live-reload dev server

### ISSUE THREAD

**Issue by GabeAtWork** [alexkorban/elmstatic#5]
Hey Alex, thank you for elmstatic, it's providing me with a good entry into Elm.

Just out of curiosity, are you still working on it, and if so do you have plans to add a live-reload server type command?

**Comment by alexkorban** [comment]
There are two aspects to this:

- Rebuilding the site when the source files change (.elm, .md + any static files)
- Actually doing the live reload in browser(s)

The first step is already doable with `chokidar` (see the docs). 

My hope is that live reload can be provided by an external tool like `browser-sync`. It doesn't seem quite right to bake it into Elmstatic itself. 

However, I've experimented with `browser-sync` and there is currently a problem: Elmstatic wipes the output directory on each build, and writes new files. `browser-sync` is unable to deal with it. 

I'd like to make some performance improvements to Elmstatic, which can be achieved by updating only what's changed instead of the whole site. I think this would also be a good opportunity to switch from deleting/re-creating files to overwriting them instead. Hopefully that would be enough to allow `browser-sync` to reload the pages.

**Comment by GabeAtWork** [comment]
That sounds like a good plan!

I've tried to make it work with `live-server` myself, adding the `elmstatic` command as a middleware and running it on source file changes. The `_site` is rebuilt, but then the changes to these files are never registered by `live-server`, so it does not reload.

An alternative solution would be to run a dev webserver which builds on demand, and refreshes the page on source file change (I suppose that's what Gatsby does?).

**Comment by alexkorban** [comment]
Live reload is possible with v0.5.0.
